[book]
title = "Intrepid Explorer Edition 4"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
default-theme = "navy"
preferred-dark-theme = "navy"
no-section-label = true
additional-css = ["theme/custom.css"]